Had enough sleep and CRUSHED all the bugs!
+ shellcheck does not complain
+ warns you when you don't use bash
+ bug fixes which are too embarassing to note here

is becoming usable ig :)

diff --git a/gsudo b/gsudo
--- a/gsudo
+++ b/gsudo
@@ -8,7 +8,7 @@ helpCommand () {
     echo "       gsudo --execute=application {options}"
     printf "\n"
     echo "Options:"
-    echo "--execute=\"app -vv --option --arg=val\"    Execute a program"
+    echo "{-x|--execute}=\"app -vv --option --arg=val\"    Execute a program"
     echo "--sleep-before-exit NUMBER[s, m, h]       Sleeps for NUMBER seconds/minutes/hours before exitting"
     echo "--stdout|-o=/path/to/stdout               Path to file where regular output should be written"
     echo "--stderr|-e=/path/to/stdout               Path to file where error messages should be written"
@@ -39,41 +39,35 @@ aboutCommand () {
 }
 
 error () {
-    printf "\e[1mgsudo:\e[21m \e[31merror:\e[0m ${1}\n"
-    exit
+    printf "\e[1mgsudo:\e[21m \e[31merror:\e[0m "
+    echo -en "${1}"
+    exit 1
 }
 
+# DEPENDENCY CHECK
+function cmnd_exists { command -v "$*"&>/dev/null;return "$?"; }
+cmnd_exists sudo || error "\e[1msudo\e[0m is not installed. Aborting."
+cmnd_exists pkexec || error "\e[1mpkexec\e[0m is not installed. Aborting."
+cmnd_exists env || error "\e[1menv\e[0m command is not available. Aborting."
+test "$(ps -p $$ -o comm=)" = "gsudo" -o "$(ps -p $$ -o comm=)" = "bash" || echo "WARNING: The current shell is not bash, but ""$(ps -p $$ -o comm=)" # In case the user runs this script with another shell (i.e., zsh gsudo.sh)
+
 #Variables
-application=$1
-commandLine=$@
-VERSION=1.3.3
+export application="$1" commandLine="$*" VERSION="1.3.3"
 #Variables: gsudo defaults
-STDOUT=/dev/tty
-STDERR=/dev/tty
-SLEEP_TIME_BEFORE_EXITTING=0s
-RUNINBACKGROUND=true
-OVERWRITE_STDOUT_FILE=">"
-OVERWRITE_STDERR_FILE=">"
-RUN_IN_BACKGROUND="&"
-ENVIRONMENT_VARIABLES="DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true"
-RUN_AS_ASKPASS=""
-RUN_IN_BACKGROUND="&"
-SHOW_RETURN_CODE=true
+export STDOUT=/dev/tty STDERR=/dev/tty SLEEP_TIME_BEFORE_EXITTING=0s RUNINBACKGROUND=true OVERWRITE_STDOUT_FILE=">" OVERWRITE_STDERR_FILE=">" RUN_IN_BACKGROUND="&" ENVIRONMENT_VARIABLES="DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true" RUN_AS_ASKPASS="" RUN_IN_BACKGROUND="&"  SHOW_RETURN_CODE=true
 
 # Gets askpass solution FIXME, add more
-if [ "$(which kdialog)" != "/usr/bin/which: no kdialog in ($PATH)" ]; then
-    SUDO_ASKPASS="askpass/kdialog_askpass.sh"
-    RUN_AS_ASKPASS="-A"
-elif [ "$(which ssh-askpass)" != "/usr/bin/which: no ssh-askpass in ($PATH)" ]; then
-    SUDO_ASKPASS="ssh-askpass"
-    RUN_AS_ASKPASS="-A"
+if cmnd_exists kdialog; then
+    export SUDO_ASKPASS="askpass/kdialog_askpass.sh" RUN_AS_ASKPASS="-A"
+elif cmnd_exists ssh_askpass; then
+    export SUDO_ASKPASS="ssh-askpass" RUN_AS_ASKPASS="-A"
 fi
 
 
 for i in "$@"; do
     case $i in
         --sleep-before-exit=*) SLEEP_TIME_BEFORE_EXITTING="${i#*=}" && shift ;;
-        -e=*|--execute=*) export commandToExec="${i#*=}"&&shift;;
+        -x=*|--execute=*) export commandToExec="${i#*=}"&&shift;;
         -\?|--help|"") helpCommand && exit ;;
         -v|--version) echo "gsudo version: v$VERSION" && exit ;;
         -a|--about) aboutCommand && exit ;;
@@ -94,11 +88,11 @@ for i in "$@"; do
         --overwrite-stdout-file) OVERWRITE_STDOUT_FILE="" && shift ;;
         --not-background) RUN_IN_BACKGROUND="" && shift ;;
         --overwrite-stderr-file) OVERWRITE_STDERR_FILE="" && shift ;;
-        --environment-append=*) ENV_TO_APPEND=" ${i#*=}" && ENVIRONMENT_VARIABLES=ENVIRONMENT_VARIABLES+ENV_TO_APPEND && shift ;;
+        --environment-append=*) ENV_TO_APPEND=" ${i#*=}" && export ENVIRONMENT_VARIABLES="${ENVIRONMENT_VARIABLES}${ENV_TO_APPEND}" && shift ;;
         --environment-variables=*) ENVIRONMENT_VARIABLES="${i#*=}" && shift ;;
         --hide-return-code) SHOW_RETURN_CODE=false && shift ;;
         --environment-file=*)
-            FILE_CONTENT=$(cat "${i#*=}")
+            FILE_CONTENT=$(cat "${i#*=}" 2>/dev/stdout)
             if [ "${FILE_CONTENT}" = "cat: ${i#*=}: Permission denied" ]; then
                 error "Failed to read from environment variable file: Permission denied"
             elif [ "${FILE_CONTENT}" = "cat: ${i#*=}: No sure file or directory" ]; then
@@ -109,22 +103,23 @@ for i in "$@"; do
             shift
         ;;
         --no-askpass) SUDO_ASKPASS="" && RUN_AS_ASKPASS=""&& shift;;
-        *) error "The following argument was not recognized: \"${i}\"\nExecute '$(basename $0) --help' for a list of available commands." && shift&&exit ;;
+        *) error "The following argument was not recognized: \"${i}\"\nExecute '$(basename "$0") --help' for a list of available commands." && shift&&exit ;;
   esac
 done
 
 #Run Command
 if [ "$commandToExec" = "" ]; then
-    printf "\e[1mgsudo:\e[21m \e[31merror:\e[0m Specify the command you want to execute using '$(basename $0) --execute=\"command\"'\nFor more information execute '$(basename $0) --help'\n"
+    error "Specify the command you want to execute using '$(basename "$0") --execute=\"command\"'\nFor more information execute '$(basename "$0") --help'\n"
 else
     echo "Launching ${commandToExec}..."
     DUMMY=$(SUDO_ASKPASS=${SUDO_ASKPASS} sudo ${RUN_AS_ASKPASS} sh -c "sudo pkexec env $ENVIRONMENT_VARIABLES $commandToExec >${OVERWRITE_STDOUT_FILE}${STDOUT} 2>${OVERWRITE_STDERR_FILE}${STDERR} ${RUN_IN_BACKGROUND}")
-    return_code=$?
+    return_code="$?" # EXPORT so shellcheck won't complain.
+    export DUMMY
     if $SHOW_RETURN_CODE; then
         #FIXME add something for background processess too
         if [ "$RUN_IN_BACKGROUND" != "&" ]; then
-            echo Return code: $return_code
+            echo "Return code: ${return_code}"
         fi
     fi
-    sleep $SLEEP_TIME_BEFORE_EXITTING
+    sleep "$SLEEP_TIME_BEFORE_EXITTING"
 fi
